### ISSUE TITLE
Species and sites omitted from constrained ordination

### ISSUE THREAD

**Issue by trichterhb** [CenterForStatistics-UGent/RCM#16]
Dear Devs,
i am currently testing your method. On a very basal level,

```
physeq = phyloseq(OTU, TAX, env)
rcm.1 <- RCM(physeq)
```

i can easily plot the site ordination, and can extract the ordination scores with

`data <- rcm.1$rMat`

for my own ggplots.

However, if i wish for constrained ordination:
`rcm.2 = RCM(physeq, covariates = var, responseFun = "nonparametric")`

I can only plot the predictor variables (located in rcm.2$alpha) when using plot(rcm.2), no matter what argument i chose with 'plotType'.
The RCM object also does not seem to contain any data for site or species ordination, but your tutorial give me the impression that they should be there.

`plotRespFun(rcm.2)
`
is working fine.

Any advise on this matter?

**Comment by sthawinke** [comment]
Dear,

Sorry for the late response. With non-parametric response functions, the only scatterplot available is indeed the predictor variables. The reason is that none of the combinations of samples/features/predictors is interpretable in this case, because of the non-linearity. plotRespFun is indeed the way to plot this combinations correctly, albeit by sacrificing a dimension.

What passage in the tutorial did you find suggesting these biplots were in fact available? Then we will adapt it.
